let jsonContent = {
  dataKhodam: [
    { id: "1", title: "Harimau Putih", desc: "This is a test desc 111" },
    { id: "2", title: "Macan Pink", desc: "This is a test desc 222" },
    { id: "3", title: "Ayam Cemani", desc: "This is a test desc 333" },
    { id: "4", title: "post title 111", desc: "This is a test desc 111" },
    { id: "5", title: "post title 222", desc: "This is a test desc 222" },
    { id: "6", title: "post title 333", desc: "This is a test desc 333" },
    { id: "7", title: "post title 111", desc: "This is a test desc 111" },
    { id: "8", title: "post title 222", desc: "This is a test desc 222" },
    { id: "9", title: "post title 333", desc: "This is a test desc 333" },
    { id: "10", title: "post title 111", desc: "This is a test desc 111" },
    { id: "11", title: "post title 222", desc: "This is a test desc 222" },
    { id: "12", title: "post title 333", desc: "This is a test desc 333" },
    { id: "13", title: "post title 111", desc: "This is a test desc 111" },
    { id: "14", title: "post title 222", desc: "This is a test desc 222" },
    { id: "15", title: "post title 333", desc: "This is a test desc 333" },
    { id: "16", title: "post title 111", desc: "This is a test desc 111" },
    { id: "17", title: "post title 222", desc: "This is a test desc 222" },
    { id: "18", title: "post title 333", desc: "This is a test desc 333" },
    { id: "19", title: "post title 111", desc: "This is a test desc 111" },
    { id: "20", title: "post title 222", desc: "This is a test desc 222" },
  ],
};
